name: 'Test Coverage Report'
description: 'Report Test Coverage to PR'
author: 'Francisco Sanchez'
inputs:
  post-commit-comment:
    required: true
    description: 'post comment on commit'
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
