name: 'Test Coverage Report'
description: 'Report Test Coverage to PR'
author: 'Francisco Sanchez'
inputs:
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  title:
    description: 'Title to add to the comment'
    required: false
  disable-comment:
    required: false
    description: 'Disable comment post/update'
    default: 'false'
  disable-build-fail:
    required: false
    description: 'Disable failing the build if no coverage files found'
    default: 'false'
  report-files:
    description: 'A list of coverage files'
    required: true
  report-types:
    description: 'A list of coverage types in the same order as the required list of files'
    required: false
  report-titles:
    description: 'A list of titles for each report in the same order as the required list of files'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
