name: 'Test Coverage Report'
description: 'Report Test Coverage to PR'
author: 'Francisco Sanchez'
inputs:
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  title:
    description: 'Title to add to the comment'
    required: false
  disable-comment:
    required: false
    description: 'Disable comment post/update'
    default: 'false'
  report-paths:
    description: |
      List of paths to test results
      Supports wildcards via [fast-glob](https://github.com/mrmlnc/fast-glob)
    required: true
  report-paths-replace-backslashes:
    description: |
      The fast-glob library that is internally used interprets backslashes as escape characters.
      If enabled, all backslashes in provided path will be replaced by forward slashes and act as directory separators.
      It might be useful when path input variable is composed dynamically from existing directory paths on Windows.
    default: 'false'
    required: false
  enable-build-fail:
    required: false
    description: 'Enable failing the build if coverage requirements are not met or no coverage files found'
    default: 'false'
  file-coverage-error-min:
    description: 'Minimal coverage required per file. Will fail if any file coverage is below this'
    required: false
  file-coverage-warn-min:
    description: 'Minimal coverage recommended per file. Will warn if any file coverage is below this'
    required: false
  report-coverage-error-min:
    description: 'Minimal coverage required per report. Will fail if any report coverage is below this'
    required: false
  report-coverage-warn-min:
    description: 'Minimal coverage recommended per report. Will warn if any report coverage is below this'
    required: false
  global-coverage-error-min:
    description: 'Minimal global coverage required. Will fail if multiple reports received and threshold not met. Ignored if only one report file received'
    required: false
  global-coverage-warn-min:
    description: 'Minimal global coverage required recommended. Will warn if multiple reports received and threshold not met. Ignored if only one report file received'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
