name: 'Test Coverage Report'
description: 'Report Test Coverage to PR'
author: 'Francisco Sanchez'
inputs:
  token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  title:
    description: 'Title to add to the comment'
    required: false
  post-commit-comment:
    required: false
    description: 'post comment on commit'
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
