name: 'build-test'
on:
  pull_request:
  push:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

      - uses: ./
        with:
          title: 'Source Code Coverage'
          report-files: |
            ./coverage/lcov.info

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          title: 'Jacoco Fixture Coverage'
          report-files: |
            ./__tests__/__fixtures__/jacoco.xml

      - uses: ./
        with:
          title: 'Lcov Fixture Coverage'
          report-files: |
            ./__tests__/__fixtures__/lcov.info

      - uses: ./
        with:
          title: 'Multi Fixture'
          report-files: |
            ./__tests__/__fixtures__/jacoco.xml
            ./__tests__/__fixtures__/lcov.info
          report-types: |
            jacoco
            lcov
          report-titles: |
            Backend Coverage
            Frontend Coverage
