name: 'build-test'
on:
  pull_request:
  push:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - run: |
          npm install
      - run: |
          npm run all

      - uses: ./
        with:
          title: 'Source Code Coverage'
          report-paths: |
            ./coverage/lcov.info

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - uses: ./
        with:
          title: 'Jacoco Fixture Coverage'
          report-paths: |
            ./__tests__/__fixtures__/jacoco.xml
          file-coverage-error-min: 60
          file-coverage-warn-min: 80
          report-coverage-error-min: 50
          report-coverage-warn-min: 70

      - uses: ./
        with:
          title: 'Lcov Fixture Coverage'
          report-paths: |
            ./__tests__/__fixtures__/lcov.info
          file-coverage-error-min: 60
          file-coverage-warn-min: 80
          report-coverage-error-min: 50
          report-coverage-warn-min: 70

      - uses: ./
        with:
          title: 'Multi Fixture'
          report-paths: |
            ./__tests__/__fixtures__/jacoco.xml
            ./__tests__/__fixtures__/lcov.info
          file-coverage-error-min: 60
          file-coverage-warn-min: 80
          report-coverage-error-min: 50
          report-coverage-warn-min: 70
          global-coverage-error-min: 40
          global-coverage-warn-min: 60
